export type Locale = "en" | "pt";

// Display label for each locale (PT shows as "BR" per request).
export const LOCALE_LABELS: Record<Locale, string> = {
  en: "EN",
  pt: "BR",
};

export const translations = {
  en: {
    "header.tagline": "Create high quality prompts with AI.",
    "footer.developedBy": "developed by Lula Rocha /",

    "generate.button": "Generate Prompt",
    "generate.loading": "Generating...",

    "task.title": "What do you want to build?",
    "task.description":
      "Describe your project, feature, or task. AI will write the prompt for you.",
    "task.placeholder":
      "Example: Build a responsive admin dashboard for a SaaS platform with real-time analytics, user management, and dark mode.",

    "upload.title": "Add context",
    "upload.description":
      "Upload a screenshot or mockup, or paste code, to guide the AI. (Optional)",
    "upload.cta": "Upload a screenshot or mockup",
    "upload.formats": "Images (PNG, JPG, GIF, SVG, WebP)",
    "upload.uploadedFiles": "Uploaded Files:",
    "upload.pasteTitle": "Paste Code Snippets",
    "upload.pasteDescription":
      "Existing code or patterns the AI should follow. (Optional)",
    "upload.pastePlaceholder": "Paste your code or text examples here...",

    "output.title": "Generated Prompt",
    "output.copy": "Copy",
    "output.copied": "Copied",
    "output.placeholder":
      "Your AI-generated prompt will appear here. You can edit it freely once it's generated.",
    "output.generating": "Generating your prompt...",
    "output.generatedBy": "Generated by",
  },
  pt: {
    "header.tagline": "Crie prompts de alta qualidade com IA.",
    "footer.developedBy": "desenvolvido por Lula Rocha /",

    "generate.button": "Gerar Prompt",
    "generate.loading": "Gerando...",

    "task.title": "O que você quer construir?",
    "task.description":
      "Descreva seu projeto, funcionalidade ou tarefa. A IA vai escrever o prompt para você.",
    "task.placeholder":
      "Exemplo: Crie um painel administrativo responsivo para uma plataforma SaaS com análises em tempo real, gerenciamento de usuários e modo escuro.",

    "upload.title": "Adicione contexto",
    "upload.description":
      "Envie uma captura de tela ou mockup, ou cole código, para guiar a IA. (Opcional)",
    "upload.cta": "Envie uma captura de tela ou mockup",
    "upload.formats": "Imagens (PNG, JPG, GIF, SVG, WebP)",
    "upload.uploadedFiles": "Arquivos enviados:",
    "upload.pasteTitle": "Cole trechos de código",
    "upload.pasteDescription":
      "Código existente ou padrões que a IA deve seguir. (Opcional)",
    "upload.pastePlaceholder": "Cole seu código ou exemplos de texto aqui...",

    "output.title": "Prompt Gerado",
    "output.copy": "Copiar",
    "output.copied": "Copiado",
    "output.placeholder":
      "Seu prompt gerado por IA aparecerá aqui. Você pode editá-lo livremente após a geração.",
    "output.generating": "Gerando seu prompt...",
    "output.generatedBy": "Gerado por",
  },
} as const;

export type TranslationKey = keyof (typeof translations)["en"];
